config/routes.rb
Sailcontroller::Application.routes.draw do
  resources :registrations

  resources :races

  resources :regatta

  resources :boats

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  get "home/index"

  
  root :to => "home#index"
end

app/controllers/regatta_controller.rb
class RegattaController < ApplicationController
  # GET /regatta
  # GET /regatta.xml
  def index
    @regatta = Regattum.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @regatta }
    end
  end

  # GET /regatta/1
  # GET /regatta/1.xml
  def show
    @regattum = Regattum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @regattum }
    end
  end

  # GET /regatta/new
  # GET /regatta/new.xml
  def new
    @regattum = Regattum.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @regattum }
    end
  end

  # GET /regatta/1/edit
  def edit
    @regattum = Regattum.find(params[:id])
  end

  # POST /regatta
  # POST /regatta.xml
  def create
    @regattum = Regattum.new(params[:regattum])

    respond_to do |format|
      if @regattum.save
        format.html { redirect_to(@regattum, :notice => 'Regattum was successfully created.') }
        format.xml  { render :xml => @regattum, :status => :created, :location => @regattum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @regattum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /regatta/1
  # PUT /regatta/1.xml
  def update
    @regattum = Regattum.find(params[:id])

    respond_to do |format|
      if @regattum.update_attributes(params[:regattum])
        format.html { redirect_to(@regattum, :notice => 'Regattum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @regattum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /regatta/1
  # DELETE /regatta/1.xml
  def destroy
    @regattum = Regattum.find(params[:id])
    @regattum.destroy

    respond_to do |format|
      format.html { redirect_to(regatta_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/regatta_helper.rb
module RegattaHelper
end

app/views/regatta/_form.html.erb
<%= form_for(@regattum) do |f| %>
  <% if @regattum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regattum.errors.count, "error") %> prohibited this regattum from being saved:</h2>

      <ul>
      <% @regattum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regatta/edit.html.erb
<h1>Editing regattum</h1>

<%= render 'form' %>

<%= link_to 'Show', @regattum %> |
<%= link_to 'Back', regatta_path %>

app/views/regatta/index.html.erb
<h1>Listing regatta</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @regatta.each do |regattum| %>
  <tr>
    <td><%= regattum.name %></td>
    <td><%= regattum.start_date %></td>
    <td><%= regattum.end_time %></td>
    <td><%= link_to 'Show', regattum %></td>
    <td><%= link_to 'Edit', edit_regattum_path(regattum) %></td>
    <td><%= link_to 'Destroy', regattum, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Regattum', new_regattum_path %>

app/views/regatta/new.html.erb
<h1>New regattum</h1>

<%= render 'form' %>

<%= link_to 'Back', regatta_path %>

app/views/regatta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @regattum.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @regattum.start_date %>
</p>

<p>
  <b>End time:</b>
  <%= @regattum.end_time %>
</p>


<%= link_to 'Edit', edit_regattum_path(@regattum) %> |
<%= link_to 'Back', regatta_path %>