config/routes.rb
Sailcontroller::Application.routes.draw do
  resources :registrations

  resources :races

  resources :regatta

  resources :boats

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  get "home/index"

  
  root :to => "home#index"
end

app/models/boat.rb
class Boat < ActiveRecord::Base
    belongs_to :boat_type
    belongs_to :user
    has_many :equipments
    has_many :sails
    has_many :crews
end

app/models/boat_type.rb
class BoatType < ActiveRecord::Base
    has_many :boats
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  # GET /boats
  # GET /boats.xml
  def index
    @boats = Boat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @boats }
    end
  end

  # GET /boats/1
  # GET /boats/1.xml
  def show
    @boat = Boat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @boat }
    end
  end

  # GET /boats/new
  # GET /boats/new.xml
  def new
    @boat = Boat.new
    @boat_types = BoatType.all.map {|bt| [bt.name, bt.id]}
    @sails = Sail.all.map {|bt| [bt.number, bt.id]}
    @equipments = Equipment.all.map {|bt| [bt.prod_number, bt.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @boat }
    end
  end

  # GET /boats/1/edit
  def edit
    @boat = Boat.find(params[:id])
  end

  # POST /boats
  # POST /boats.xml
  def create
      eqs = []
      puts params
      params[:boat][:equipments].each do |i|
          eqs << Equipment.find(i)
      end
      params[:boat][:equipments] = eqs
      @boat = Boat.new(params[:boat])

    respond_to do |format|
      if @boat.save
        format.html { redirect_to(@boat, :notice => 'Boat was successfully created.') }
        format.xml  { render :xml => @boat, :status => :created, :location => @boat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @boat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boats/1
  # PUT /boats/1.xml
  def update
    @boat = Boat.find(params[:id])

    respond_to do |format|
      if @boat.update_attributes(params[:boat])
        format.html { redirect_to(@boat, :notice => 'Boat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @boat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.xml
  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy

    respond_to do |format|
      format.html { redirect_to(boats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_for(@boat) do |f| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Baad_type %><br />
	<%= f.select :boat_type_id, options_for_select(@boat_types) %>
  </div>
  <div class="field">
    <%= f.label :Udstyr %><br />
	<%= f.select :equipments, options_for_select(@equipments),{},{:multiple=>true} %>
  </div>
  <div class="field">
    <%= f.label :Sejl %><br />
	<%= f.select :sails, options_for_select(@sails), {} ,{:multiple=>true}%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing boat</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<h1>Listing boats</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boats.each do |boat| %>
  <tr>
    <td><%= boat.number %></td>
    <td><%= boat.name %></td>
    <td><%= link_to 'Show', boat %></td>
    <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
    <td><%= link_to 'Destroy', boat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New boat</h1>

<%= render 'form' %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @boat.number %>
</p>

<p>
  <b>Name:</b>
  <%= @boat.name %>
</p>


<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>